# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_food_is_spicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_spicy',
            field=models.BooleanField(default=False),
        ),
    ]
