# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 01:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_food_is_spicy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='address',
            new_name='comment',
        ),
    ]
